services:
  frontend:
    build:
      context: .
      target: dev
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - WDS_SOCKET_PORT=5173
    restart: unless-stopped
    networks:
      - story-tailer-net
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]

networks:
  story-tailer-net:
    external: true
    name: story-tailer-net
